#!/bin/sh
#
# Startup wrapper for Slideshow
#
# Copyright (C) 2008, David Sveningsson <ext@sidvind.com>
#
# Licenced under the GNU Affero General Public License, version 3
#

export SLIDESHOW_DATA_DIR="`pwd`/data"
export SLIDESHOW_PLUGIN_DIR="`pwd`/src/transitions:`pwd`/src/assembler"
export SDL_VIDEO_X11_XRANDR 0
export SLIDESHOW_NO_ABORT ""

case `basename $0` in
    slideshow-gdb)
	exec gdb --cd /home/ext/slideshow --args `pwd`/src/slideshow $*
	;;
    slideshow-valgrind)
	exec valgrind $*
	;;
    slidetool)
	exec src/slidetool $*
	;;
    *)
	exec src/slideshow $*
	;;
esac;
